spring.application.name=PaymentService
server.port=5006

# ================= DATABASE =================
spring.datasource.url=jdbc:mysql://localhost:3306/salonbooking?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.type.descriptor.sql=TRACE

# ================= RABBITMQ =================
spring.rabbitmq.port=5672
spring.rabbitmq.host=localhost
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest


# ================= EUREKA CLIENT =================
eureka.instance.prefer-ip-address=true
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8070/eureka/

# ================= PAYMENT CONFIG =================
razorpay.api.key=rzp_test_SMgvWmXb88hNFf
razorpay.api.secret=NQzg8KWvuzoO4hZtO65BtT7U
stripe.api.key=yourstripeapikey

# ================= RESILIENCE4J =================

# User Circuit Breaker
resilience4j.circuitbreaker.instances.userCB.register-health-indicator=true
resilience4j.circuitbreaker.instances.userCB.sliding-window-size=10
resilience4j.circuitbreaker.instances.userCB.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.userCB.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.userCB.wait-duration-in-open-state=10s

# UserById Circuit Breaker
resilience4j.circuitbreaker.instances.userByIdCB.register-health-indicator=true
resilience4j.circuitbreaker.instances.userByIdCB.sliding-window-size=10
resilience4j.circuitbreaker.instances.userByIdCB.minimum-number-of-calls=5
resilience4j.circuitbreaker.instances.userByIdCB.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.userByIdCB.wait-duration-in-open-state=10s

# Retry
resilience4j.retry.instances.userRetry.max-attempts=3
resilience4j.retry.instances.userRetry.wait-duration=2s

# Timeout
resilience4j.timelimiter.instances.userCB.timeout-duration=3s
resilience4j.timelimiter.instances.userByIdCB.timeout-duration=3s

# ================= LOGGING =================
logging.level.io.github.resilience4j=DEBUG



