version: "3.8"

networks:
  salon-network:
    driver: bridge

volumes:
  salon-db-data:

services:
  # ================= MYSQL =================
  salon-db:
    image: mysql:8
    container_name: salon-db
    ports:
      - "3301:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: salonbooking
    volumes:
      - salon-db-data:/var/lib/mysql
    networks:
      - salon-network

  # ================= EUREKA SERVER =================
  eurekaserver:
    image: ankitagarwal2210/eurekaserver
    container_name: eurekaserver
    restart: always
    ports:
      - "8070:8070"
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8070/actuator/health/readiness | grep UP || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - salon-network


  # ================= API GATEWAY =================
  apigateway:
    image: ankitagarwal2210/apigateway
    container_name: apigateway
    ports:
      - "5000:5000"
    environment:
      SPRING_APPLICATION_NAME: ApiGateway
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
    depends_on:
      - eurekaserver
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/actuator/health/readiness | grep UP || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - salon-network


  # ================= KEYCLOAK =================
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.3
    container_name: keycloak
    restart: always
    command: start-dev
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    networks:
      - salon-network

  # ================= RABBITMQ =================
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - salon-network

  # ================= USER SERVICE =================
  userservice:
    image: ankitagarwal2210/userservice
    container_name: userservice
    restart: always
    ports:
      - "5001:5001"
    depends_on:
      - salon-db
      - eurekaserver
    environment:
      SPRING_APPLICATION_NAME: UserService
      SPRING_DATASOURCE_URL: jdbc:mysql://salon-db:3306/salonbooking
      SPRING_DATASOURCE_USERNAME: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
    networks:
      - salon-network

  # ================= SALON SERVICE =================
  salonservice:
    image: ankitagarwal2210/salonservice
    container_name: salonservice
    restart: always
    ports:
      - "5002:5002"
    depends_on:
      - salon-db
      - eurekaserver
    environment:
      SPRING_APPLICATION_NAME: SalonService
      SPRING_DATASOURCE_URL: jdbc:mysql://salon-db:3306/salonbooking
      SPRING_DATASOURCE_USERNAME: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
    networks:
      - salon-network

  # ================= CATEGORY SERVICE =================
  categoryservice:
    image: ankitagarwal2210/categoryservice
    container_name: categoryservice
    restart: always
    ports:
      - "5003:5003"
    depends_on:
      - salon-db
      - eurekaserver
    environment:
      SPRING_APPLICATION_NAME: "CategoryService"
      SPRING_DATASOURCE_URL: "jdbc:mysql://salon-db:3306/salonbooking"
      SPRING_DATASOURCE_USERNAME: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
    networks:
      - salon-network

  # ================= OFFERING SERVICE =================
  offeringservice:
    image: ankitagarwal2210/offeringservice
    container_name: offeringservice
    ports:
      - "5004:5004"
    depends_on:
      - salon-db
      - eurekaserver
    environment:
      SPRING_APPLICATION_NAME: "OfferingService"
      SPRING_DATASOURCE_URL: "jdbc:mysql://salon-db:3306/salonbooking"
      SPRING_DATASOURCE_USERNAME: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
    networks:
      - salon-network

#   ================= BOOKING SERVICE =================
  bookingservice:
    image: ankitagarwal2210/bookingservice
    container_name: bookingservice
    restart: always
    ports:
      - "5005:5005"
    depends_on:
      - salon-db
      - eurekaserver
    environment:
      SPRING_APPLICATION_NAME: "BookingService"
      SPRING_DATASOURCE_URL: "jdbc:mysql://salon-db:3306/salonbooking"
      SPRING_DATASOURCE_USERNAME: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
    networks:
      - salon-network

  # ================= PAYMENT SERVICE =================
  paymentservice:
    image: ankitagarwal2210/paymentservice
    container_name: paymentservice
    restart: always
    ports:
      - "5006:5006"
    depends_on:
      - salon-db
      - eurekaserver
    environment:
      SPRING_APPLICATION_NAME: "PaymentService"
      SPRING_DATASOURCE_URL: "jdbc:mysql://salon-db:3306/salonbooking"
      SPRING_DATASOURCE_USERNAME: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
    networks:
      - salon-network

  # ================= NOTIFICATION SERVICE =================
  notificationservice:
    image: ankitagarwal2210/notificationservice
    container_name: notificationservice
    restart: always
    ports:
      - "5007:5007"
    depends_on:
      - salon-db
      - eurekaserver
    environment:
      SPRING_APPLICATION_NAME: "NotificationService"
      SPRING_DATASOURCE_URL: "jdbc:mysql://salon-db:3306/salonbooking"
      SPRING_DATASOURCE_USERNAME: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
    networks:
      - salon-network

  # ================= REVIEW SERVICE =================
  reviewservice:
    image: ankitagarwal2210/reviewservice
    container_name: reviewservice
    restart: always
    ports:
      - "5008:5008"
    depends_on:
      - salon-db
      - eurekaserver
    environment:
      SPRING_APPLICATION_NAME: "ReviewService"
      SPRING_DATASOURCE_URL: "jdbc:mysql://salon-db:3306/salonbooking"
      SPRING_DATASOURCE_USERNAME: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
    networks:
      - salon-network
