export const CREATE_SALON = {
    REQUEST: "CREATE_SALON_REQUEST",
    SUCCESS: "CREATE_SALON_SUCCESS",
    FAILURE: "CREATE_SALON_FAILURE"
};

export const UPDATE_SALON = {
    REQUEST: "UPDATE_SALON_REQUEST",
    SUCCESS: "UPDATE_SALON_SUCCESS",
    FAILURE: "UPDATE_SALON_FAILURE"
};

export const FETCH_SALONS = {
    REQUEST: "FETCH_SALONS_REQUEST",
    SUCCESS: "FETCH_SALONS_SUCCESS",
    FAILURE: "FETCH_SALONS_FAILURE"
};

export const FETCH_SALON_BY_ID = {
    REQUEST: "FETCH_SALON_BY_ID_REQUEST",
    SUCCESS: "FETCH_SALON_BY_ID_SUCCESS",
    FAILURE: "FETCH_SALON_BY_ID_FAILURE"
};

export const FETCH_SALON_BY_OWNER_ID = {
    REQUEST: "FETCH_SALON_BY_OWNER_ID_REQUEST",
    SUCCESS: "FETCH_SALON_BY_OWNER_ID_SUCCESS",
    FAILURE: "FETCH_SALON_BY_OWNER_ID_FAILURE"
};

export const SEARCH_SALONS = {
    REQUEST: "SEARCH_SALONS_REQUEST",
    SUCCESS: "SEARCH_SALONS_SUCCESS",
    FAILURE: "SEARCH_SALONS_FAILURE"
};






